### ISSUE TITLE
EAN13 generates UPC-A when barcode starts with zero

### ISSUE THREAD

**Issue by bommelding** [picqer/php-barcode-generator#10]
In the current 0.2 version the EAN13 barcode which should be generated, now generates a UPC-A barcode, if the barcode starts with a zero (0). 
Test environment uses PHP 5.6.1.

**Comment by Epenance** [comment]
Was there ever found a solution for this?

**Comment by iamraju** [comment]
Not sure if that is an issue but same goes here. Leading zero is skipped for some reason while reading.

Another problem is that if I print the barcode below 40mm size labels, the barcode is not printed correctly and does not get read by scanner. The barcode generated by other software like SATO are being read correctly.

**Comment by casperbakker** [comment]
This should be fixed with our new v2 version in #91
