### ISSUE TITLE
[Feature] Make widthFactor float

### ISSUE THREAD

**Issue by kykint** [picqer/php-barcode-generator#100]
Hello!
Now widthFactor is integer, so it's impossible to make it for example 1.5, or something similar. But for SVG and HTML it makes sense. 
It would be great to make widthFactor float. I've checked and it works fine.

**Comment by haivala** [comment]
I think the HTML version should support percentages and all of them should have optionally the actual code under the barcode.

**Comment by casperbakker** [comment]
Added in #126
