### ISSUE TITLE
Line break on each bar when barcode is sent by email

### ISSUE THREAD

**Issue by marciosironi** [picqer/php-barcode-generator#101]
I use the barcode generator in my Woocommerce store.
For each purchase made, I generate a barcode that is available in the "my account" of the customer, and also sent by email.
The barcode generated in "my account" is perfect, but what is generated for sending in the customer's email, results in a broken barcode.
Instead of each bar being side by side, there is a line break with each new bar.
See image: [https://prnt.sc/slzm0o](url)

I'm generating HTML barcode. I've tried using PNG, but the image is not displayed.
How can I solve?

**Comment by sk0ch** [comment]
/vendor/picqer/php-barcode-generator/src/BarcodeGeneratorHTML.php
Сhange on:
`public function getBarcode($barcode, $type, int $widthFactor = 2, int $height = 30, string $foregroundColor = 'black')
    {
        $barcodeData = $this->getBarcodeData($barcode, $type);

        $html = '<div style="font-size:0;position:relative;width:' . ($barcodeData->getWidth() * $widthFactor) . 'px;height:' . ($height) . 'px;">' . PHP_EOL;

        $positionHorizontal = 0;
        /** @var BarcodeBar $bar */
        foreach ($barcodeData->getBars() as $bar) {
            $barWidth = round(($bar->getWidth() * $widthFactor), 3);
            $barHeight = round(($bar->getHeight() * $height / $barcodeData->getHeight()), 3);

            if ($bar->isBar() && $barWidth > 0) {
                $positionVertical = round(($bar->getPositionVertical() * $height / $barcodeData->getHeight()), 3);
                // draw a vertical bar
                $html .= '<div style="float:left; background-color:' . $foregroundColor . ';width:' . $barWidth . 'px;height:' . $barHeight . 'px; margin-left:' . ( $positionHorizontal - $prevPositionHorizontal ) . 'px;">&nbsp;</div>' . PHP_EOL;
            }

            $prevPositionHorizontal = $positionHorizontal;
			$positionHorizontal += $barWidth;
        }

        $html .= '</div><div style="clear:both"></div>' . PHP_EOL;

        return $html;
    }`

**Comment by marciosironi** [comment]
Works perfectly! 
Thanks
