### ISSUE TITLE
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{'

### ISSUE THREAD

**Issue by serkor** [picqer/php-barcode-generator#104]
`<?php

namespace Picqer\Barcode\Types;

use Picqer\Barcode\Barcode;

interface TypeInterface
{
    public function getBarcodeData(string $code): Barcode; //19 line
}`

//error

1) PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /var/www/site.com/includes/libs/php-barcode-generator-master/src/Types/TypeInterface.php on line 9

2) PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /var/www/site.com/includes/libs/php-barcode-generator-master/src/Helpers/BinarySequenceConverter.php on line 13

Use PHP 7.3-7.4

how to solve?

**Comment by casperbakker** [comment]
I don't think you are really using PHP 7.3 or 7.4, because this seems like an error that PHP does not understand type hinted returns in interfaces. This is added in PHP 7.1: https://medium.com/@3lpsy/php-7-1-type-hinting-return-values-with-interfaces-and-classes-a266361424b2
