### ISSUE TITLE
Cannot generate characters '96'

### ISSUE THREAD

**Issue by ragil000** [picqer/php-barcode-generator#107]
I have a barcode characters '20190096' then I generate it into a barcode. When I scan using a barcode scanner, what is read by the barcode scanner is only the character '201900' character '96' is missing. Then I try to add one digit behind my previous barcode characters so that it becomes '201900961' then I generate again and I scan again using a barcode scanner, apparently all the characters read '201900961'. Then I tried again to change my barcode characters to '20190196' and what happened was only the characters '201901' that was read, the '96' characters disappeared. Then I tried again to '20190076' and it turned out to be '20190076'. I did this experiment over and over, until finally I concluded that the character '96' did not work in generate.

**Comment by joeybab3** [comment]
What type of barcode were you attempting to generate?

**Comment by ragil000** [comment]
type 128

**Comment by casperbakker** [comment]
It is working here, the barcode should be valid when using Code 128 with "20190096". Maybe a bug or setting with your scanner?
