### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by xpackal5** [picqer/php-barcode-generator#108]
Hi. EAN-13 generator fail.

File: .../src/Types/TypeEanUpcBase.php:214    

```204:            }
205:    
206:            return $barcode;
207:        }
208:    
209:        protected function calculateChecksumDigit(string $code)
210:        {
211:            // calculate check digit
212:            $sum_a = 0;
213:            for ($i = 1; $i < $this->length - 1; $i += 2) {
214:                $sum_a += $code[$i];
215:            }
216:            if ($this->length > 12) {
217:                $sum_a *= 3;
218:            }

**Comment by joeybab3** [comment]
Can you post the code you were running that caused this error message?

**Comment by xpackal5** [comment]
$generator = new Picqer\Barcode\BarcodeGeneratorHTML();
echo $generator->getBarcode('4569872365789', $generator::TYPE_EAN_13);

Another generators (PNG, JPG etc does not work too)

PHP7.4

**Comment by casperbakker** [comment]
Your barcode is not correct. EAN13 is really strict, and your '9' code in the end is not a valid checksum of the 12 previous chars. The latest version of this library will give you a `Picqer\Barcode\Exceptions\InvalidCheckDigitException` exception to explain what you did wrong.

If you really want "4569872365789" in a barcode, you should use CODE_128.
