### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated in 7.4

### ISSUE THREAD

**Issue by jessegall** [picqer/php-barcode-generator#110]
Hello,

Could you update your package for the array syntax with curly braces is deprecated in php 7.4.

Thanks,

Jesse

**Comment by joeybab3** [comment]
I thought this was fixed?

https://github.com/picqer/php-barcode-generator/pull/98

**Comment by casperbakker** [comment]
That's right. The latest version of this library supports PHP 7.4, no curly braces in there. You probably run not the latest version.
