### ISSUE TITLE
why

### ISSUE THREAD

**Issue by oksky44** [picqer/php-barcode-generator#112]
A PHP Error was encountered

Severity: 8192

Message: Array and string offset access syntax with curly braces is deprecated

Filename: src/BarcodeGenerator.php

Line Number: 293

Backtrace:

File: /Applications/XAMPP/xamppfiles/htdocs/ozsky/vendor/composer/ClassLoader.php
Line: 444
Function: _error_handler

File: /Applications/XAMPP/xamppfiles/htdocs/ozsky/vendor/composer/ClassLoader.php
Line: 444
Function: include

File: /Applications/XAMPP/xamppfiles/htdocs/ozsky/vendor/composer/ClassLoader.php
Line: 322
Function: Composer\Autoload\includeFile

File: /Applications/XAMPP/xamppfiles/htdocs/ozsky/vendor/picqer/php-barcode-generator/src/BarcodeGeneratorHTML.php
Line: 5
Function: spl_autoload_call

File: /Applications/XAMPP/xamppfiles/htdocs/ozsky/vendor/composer/ClassLoader.php
Line: 444
Function: include

File: /Applications/XAMPP/xamppfiles/htdocs/ozsky/vendor/composer/ClassLoader.php
Line: 322
Function: Composer\Autoload\includeFile

**Comment by joeybab3** [comment]
#110 #105 #98 #97
