### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by shajeermhmmd** [picqer/php-barcode-generator#113]
**PHP-Barcode-Generator allows only for the numeric values, strings or mixed strings are not supporting, any solution to fix this issue? Please refer to the error shown below. Thank you** 

**PHP Code:** 
![image](https://user-images.githubusercontent.com/12708552/95446407-ecdbab00-0968-11eb-9cad-3de4044f3fe4.png)

---------------------------------------------------------------------------------------------------------------------------

**A PHP Error was encountered**
**Severity: Warning**

**Message: A non-numeric value encountered**

**Filename: Types/TypeEanUpcBase.php**

Line Number: 214

Backtrace:

File: C:\wamp64\www\front_end\codeigniter\vendor\picqer\php-barcode-generator\src\Types\TypeEanUpcBase.php
Line: 214
Function: _error_handler

File: C:\wamp64\www\front_end\codeigniter\vendor\picqer\php-barcode-generator\src\Types\TypeEanUpcBase.php
Line: 40
Function: calculateChecksumDigit

File: C:\wamp64\www\front_end\codeigniter\vendor\picqer\php-barcode-generator\src\BarcodeGenerator.php
Line: 101
Function: getBarcodeData

File: C:\wamp64\www\front_end\codeigniter\vendor\picqer\php-barcode-generator\src\BarcodeGeneratorPNG.php
Line: 54
Function: getBarcodeData

File: C:\wamp64\www\front_end\codeigniter\application\views\public\themes\admin\print_barcode.php
Line: 275
Function: getBarcode

File: C:\wamp64\www\front_end\codeigniter\application\views\public\themes\admin\layout.php
Line: 5
Function: view

File: C:\wamp64\www\front_end\codeigniter\application\controllers\Admin.php
Line: 793
Function: view

File: C:\wamp64\www\front_end\codeigniter\index.php
Line: 316
Function: require_once

**Comment by casperbakker** [comment]
Type EAN 13 is very strict and does not support anything else then chars 0-9, it should be 12 or 13 with the right checksum. That is in the EAN 13 specs.

If you want something else in the barcode, you should use Code128.

**Comment by shajeermhmmd** [comment]
Thank you, I changed to CODE_128 now it is working
