### ISSUE TITLE
how to generate barcode with string included in it 

### ISSUE THREAD

**Issue by pratikraman-dev** [picqer/php-barcode-generator#115]
i have a barcode with string in it it gives me error on Characters like G 

000001GOODIESUWL
000002GOODIESUWL
000003GOODIESUWL
000004GOODIESUWL
000005GOODIESUWL
000006GOODIESUWL

![image](https://user-images.githubusercontent.com/8825570/100416779-4c228580-30a5-11eb-80e2-d951087d1bd5.png)

**Comment by stephangroen** [comment]
Those chars are now allowed in codabar. See: https://www.keyence.com/ss/products/auto_id/barcode_lecture/basic/barcode-types/

**Comment by pratikraman-dev** [comment]
Thanks i found solution needed to use codebar128
