### ISSUE TITLE
Barcode not redering in IE6 and IE7

### ISSUE THREAD

**Issue by manithink** [picqer/php-barcode-generator#12]
I am generating TYPE_CODE_128_A barcode.
It works on Chrome and Mozilla. Also works on IE 8 and above versions.
But not rendering in IE6 and IE7.

Please help me.
Thanks in advance.

**Comment by stephangroen** [comment]
This is an issue with your front-end code, not with the package. IE6 might not support your style of image inclusion (for example inline images are not supported in IE6).  You will need to save the barcode as a JPG and show that on the page in the normal way, with the JPG file as the source.

**Comment by manithink** [comment]
Thank you for reply.
Nope.
No luck with jpg file as well.

Here is my code,

<?php
    require("new_barcode/BarcodeGenerator.php");  
    require("new_barcode/BarcodeGeneratorHTML.php");
    require("new_barcode/BarcodeGeneratorPNG.php");
    require("new_barcode/BarcodeGeneratorJPG.php");
    ?>
    <br>
    <?
    function barcodeGeneratortest6(){
        $generator = new \Picqer\Barcode\BarcodeGeneratorPNG();
        $data = base64_encode($generator->getBarcode("testm567", $generator::TYPE_CODE_128_A, 2, 50));
        echo "<img  style='width:240px;height:35px' src='data:image/png;base64,".$data."'></img><br />";  
    }
    barcodeGeneratortest6();
    ?>
    <br>
    <?
    function barcodeGeneratortest7(){
        $generator = new \Picqer\Barcode\BarcodeGeneratorJPG();
        $data = base64_encode($generator->getBarcode("testm567", $generator::TYPE_CODE_128_A, 2, 50));
        echo "<img  style='width:240px;height:35px' src='data:image/jpeg;base64,".$data."'></img><br />";  
    }
    barcodeGeneratortest7();
?>

**Comment by manithink** [comment]
![barcodetest](https://cloud.githubusercontent.com/assets/8181185/17018088/c5bc07f0-4f53-11e6-8f43-cce863cbb2ee.PNG)

I have attached screenshot of IE 6

**Comment by stephangroen** [comment]
They way you echo it to the browser is not in any way related to this package. This package is only used for the generation of the barcode, which is does well. Please consider asking at a site like Stackoverflow.
