### ISSUE TITLE
Not compatible with php version 7.4.*

### ISSUE THREAD

**Issue by ghost** [picqer/php-barcode-generator#124]
While installing the package I am getting error https://www.awesomescreenshot.com/image/6444753
![Screenshot by Li](https://user-images.githubusercontent.com/47355715/110116192-2829bb00-7ddd-11eb-9ff7-9e930f588be6.png)

**Comment by casperbakker** [comment]
The latest version of this package is 2.1.0, which has full support for PHP 7.4 and 8.0. It looks like webkul/barcode-inventory uses version 0.3.0 which is not compatible with PHP 7.4. You could check webkul/barcode-inventory if there is a newer version available that supports newer version of this library.
