### ISSUE TITLE
How to add numbers in barcodes

### ISSUE THREAD

**Issue by flames943** [picqer/php-barcode-generator#125]
Hello.

First of all I want to give you my congratulations for such an excellent liberia created for the generation of barcodes.

my question is how can I add the barcode characters below it?

pass from a barcode without characters:

![nochar](https://user-images.githubusercontent.com/80230785/110263133-56450180-7f7b-11eb-9079-b75d84ff540b.png)

to this barcode with characters:

![char](https://user-images.githubusercontent.com/80230785/110263159-6e1c8580-7f7b-11eb-92c0-ecc75eb14625.png)

I generated that image in photoshop to understand what I want to do with the php code, since with code I can't solve it and I need it to be able to generate code with the get method.

**Comment by louis123562** [comment]
Hey man,

i dont know if you are familiar with imagick, but with it you could add your numbers to it:

1. generate the image of barcode
2. load file/binary into imagick
3. create another image in imagick, which holds your numbers
4. combine both images with imagick

Sure it is a bit of work, but it is a possible solution.

I would like to hear other opinons.

**Comment by casperbakker** [comment]
Thanks for your kind words. 

At this moment it is not something that this library supports. You can use the outputted image as a source to add text to it with GD or Imagick. You can just search for how to add text with GD/Imagick to an existing image.
