### ISSUE TITLE
Possible to change width for BarcodeGeneratorHTML from int to float 

### ISSUE THREAD

**Issue by davedarko** [picqer/php-barcode-generator#128]
Hey there,

I know you have the wonderful dynamic version, but would it be possible for you to change the type of width in the function getBarcode to something floaty to allow for different sizes that way? Changing the type allowed us to use the factor 1.5 for width with no problem. I don't even think that's an issues but CSS allows for fractional pixels anyways.

This is a somewhat lazy hot weather request, where I try not to work too much, but also am aware that once we update, our change could be lost and nobody would be wiser :D

Thanks for the wonderful generator,
cheers Dave

**Comment by casperbakker** [comment]
Hi Dave,

Thanks for your nice words.

I do not understand your question completely. The primary generators all have the same interface, with integers. There is a specific [dynamic](https://github.com/picqer/php-barcode-generator/blob/main/src/BarcodeGeneratorDynamicHTML.php) version to use floats like you want. 

So you can use `BarcodeGeneratorDynamicHTML` with a factor of 1.5 already. So I am not sure what your request is.

**Comment by davedarko** [comment]
Hey,

So the function getBarcode($barcode, $type, int $widthFactor = 2, int $height = 30, array $foregroundColor = [0, 0, 0]) defines widthFactor as int, if we remove that int definition, we can also use widthFactor 1.5 with everything and it scales nicely. But I think we just have to use the correct function (BarcodeGeneratorDynamicHTML) instead.

**Comment by casperbakker** [comment]
But that is what the `BarcodeGeneratorDynamicHTML` method is for. Changing the interface for the `BarcodeGeneratorHTML` is a breaking change and would need a new mayor version number. Not something I think is worth it for this change. That is why we created a new class with the dynamic functionality.
