### ISSUE TITLE
Is there a way to use this barcode in PHP version 5.6 ?

### ISSUE THREAD

**Issue by careerdimasprayoga** [picqer/php-barcode-generator#129]
is there a way to use this barcode in PHP version 5.6 ?
I have to use barcode but my PHP project is very outdated.

**Comment by casperbakker** [comment]
@careerdimasprayoga Yes, you can use version https://github.com/picqer/php-barcode-generator/releases/tag/v0.3. That is the last one that is targeted for >= 5.4.

The interface works a bit differently with that version, but just check the readme for version 0.3 and you can figure it out.
