### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by AndreyNazarchuk** [picqer/php-barcode-generator#13]
The example at the bottom of the ReadMe does not work.

**Comment by stephangroen** [comment]
Without any info it's hard to help.

**Comment by AndreyNazarchuk** [comment]
The example at the bottom of the Readme does don't work, chrome (canary)
just shows a broken image logo. None of the code was changed except for the
text(just different numbers). PHP 7.0 cgi, Nginx.

**Comment by stephangroen** [comment]
The output to the browser is not part of this package. If you can create a barcode and get a JPG from it, it works.

**Comment by AndreyNazarchuk** [comment]
That is what's not working.

**Comment by casperbakker** [comment]
The example on the read me is perfectly fine. If it does not render an image in your browser, then your PHP probably echo's an error inside the img tag. In most cases, not the right GD packages are installed.

Please use your own PHP knowledge to debug your personal situation.

**Comment by AndreyNazarchuk** [comment]
Anyone else that runs into this issue, the problem was because of an error being put into the image.

go to your web server (ubuntu) and run

`sudo apt-get install php7.0-gd`

for php 5 run

`sudo apt-get install php-gd`

then restart your php and web server

**Comment by casperbakker** [comment]
It is recommended for new users to first try the example that is shown in 'usage' in the readme. That will show you any errors right away.

The 'examples' section is for extended examples.

I will clarify this in the readme.
