### ISSUE TITLE
add generated numeric code below barcode

### ISSUE THREAD

**Issue by rodri154321** [picqer/php-barcode-generator#130]
How to add the numeric code after the barcode?

**Comment by joeybab3** [comment]
#125, #111 cover this. In essence, it's not supported currently.

**Comment by rodri154321** [comment]
> [# 125](https://github.com/picqer/php-barcode-generator/issues/125) , [# 111](https://github.com/picqer/php-barcode-generator/issues/111) cubren esto. En esencia, actualmente no es compatible.

Oh thank you very much

**Comment by voxp1b5** [comment]
yes - add -> line = 48 / file = vendo/......./src/BarcodeGeneratorSvg.php
`$svg .= '<text x="'.( $width-300).'" y="'.($barHeight+35).'" font-family="Verdana" font-size="40" >'.$barcode.'</text>';`
change = -300 and +35
