### ISSUE TITLE
vendor/autoload.php  nee this file 

### ISSUE THREAD

**Issue by Subbaiyan** [picqer/php-barcode-generator#131]
Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in D:\xampp\htdocs\barcode\generate-examples.php on line 7

**Comment by joeybab3** [comment]
Did you do a `composer require` of this library or did you just download it from github?

**Comment by casperbakker** [comment]
You need Composer to use this package like the readme notes. You can use it without ofcourse, but then you need to include the files yourself.

Learn more about Composer here: https://getcomposer.org/doc/00-intro.md
