### ISSUE TITLE
Use without composer Slim PHP framework

### ISSUE THREAD

**Issue by markosole** [picqer/php-barcode-generator#133]
Hi all, I am trying to install this and use on Slim PHP framework but without using composer. 
I am using another library installed manually and it works fine, just can't get this working, I am getting server error 500

I tried this:

`use Picqer\Barcode\BarcodeGeneratorHTML;`

and than in function calling this:

`$generator = new Picqer\Barcode\BarcodeGeneratorHTML();`

Any tips how to install and use in Slim.

Thx

**Comment by joeybab3** [comment]
The first step would probably be enabling error output so you can see what’s causing the 500 error
