### ISSUE TITLE
Wrong encoding for some characters in type Code 93

### ISSUE THREAD

**Issue by Bernhard-Krop** [picqer/php-barcode-generator#138]
HI there!

Code 93 uses a basic character set of 43 characters (upper case letters A-Z, numbers 0-9, as well as the following special characters: - . $ / + % SPACE). In \Picqer\Barcode\Types\TypeCode93::getBarcodeData(), the encoding array ($encode in line 71) does use the wrong encoding for the following characters:

* $: `chr(129) . 'D'` should be `'$'`
*  /: `chr(129) . 'O'` should be `'/'`
* +; `chr(129) . 'K'` should be `'+'`
* %: `chr(129) . 'E'` should be `'%'`

This wrong encodings should be fixed.

Kind regards,

Bernhard

REFERENCE: https://en.wikipedia.org/wiki/Code_93#Full_ASCII_Code_93

**Comment by casperbakker** [comment]
Thanks @Bernhard-Krop, I fixed these encodings.
