### ISSUE TITLE
Text in the bottom of the barcode

### ISSUE THREAD

**Issue by robertripoll** [picqer/php-barcode-generator#14]
Hello,

Is there any way I can show the actual code of the generated barcode or a custom text in the bottom part of the generated barcode image?

I would also like to suggest this as a feature for future versions, which I found useful.

Thanks in advance.

**Comment by casperbakker** [comment]
At this moment that is not possible. But you could add it to the code if you like and send in a PR.

**Comment by robertripoll** [comment]
I've added the text thing at the bottom of the generated barcode, which shows the code as text.

I will make a Pull Request today.

**Comment by dmarklund** [comment]
@UngarMax Hey Ungar, I'm looking to solve this as well, did you manage to create a PR?

**Comment by angeldev20** [comment]
Test is not supported yet?

**Comment by stephangroen** [comment]
No PR has been submitted yet.

**Comment by robertripoll** [comment]
I will not submit a Pull Request since I just have modified the original source code to my own liking.

https://gist.github.com/UngarMax/eb102068fd83c176172fdbb2327d2624

**Comment by filiperhiza** [comment]
Yes, it is possible. Just use the file BarcodeGeneratorPNGWithNumber.php
