### ISSUE TITLE
Error with checksum of Code 39E

### ISSUE THREAD

**Issue by Bernhard-Krop** [picqer/php-barcode-generator#140]
Hi there!

I've found another error. When creating a barcode of type Code 39 Extended with Checksum and the content of the barcode contains a character which is not part of the basic Code 39 character set, then in \Picqer\Barcode\Types\TypeCode39::checksum_code39() PHP notices arise.

The reason for that is, that in line 325 it is tried to access the first element of an empty array, which has been created in the line above: `$k = array_keys($chars, $code[$i]);` with $chars holding only the basic characters of Code 39.

A possible solution would be to append the ??-operator to line 325: `$sum += $k[0] ?? 0;`.

Kind regards,

Bernhard Krop

EDIT 1:

It seems I made a little mistake. The extended charset is converted into the basic charset before the checksum will be calculated. Therefore, the error is not in the checksum calculation. Instead, the error is in the encoding itself.
In \Picqer\Barcode\Types\TypeCode39::encode_code39_ext(), the $encode array has a typo. In line 135, chr(11) is encoded into '£K', which is wrong; it must be '$K' (according to [Wikipedia](https://en.wikipedia.org/wiki/Code_39#Full_ASCII_Code_39)). The character '£' is causing the PHP notices while calculating the checksum.

**Comment by casperbakker** [comment]
Thanks @Bernhard-Krop, great find!
