### ISSUE TITLE
Eror getBarcode

### ISSUE THREAD

**Issue by Raihanrmdn** [picqer/php-barcode-generator#141]
$generator = assets/vendor/picqer/php-barcode-generator/src/BarcodeGenerator.php
        echo $generator->getBarcode('081231723897', $generator::TYPE_CODE_128);

i've got error

Type: ParseError

Message: syntax error, unexpected 'echo' (T_ECHO)

Filename: D:\xampp\htdocs\inventory\application\controllers\Admin.php

Line Number: 221

**Comment by joeybab3** [comment]
You didn't put a semicolon after the first line
