### ISSUE TITLE
[feature] set background color and padding (or border)

### ISSUE THREAD

**Issue by pubi** [picqer/php-barcode-generator#143]
We are using the library in one of our mobile app and it would be nice if we could set the border around the code. Why? Problem is when on the mobile the dark mode is enabled, because code merges on the left and right side with black background. Is there any workaround with Imagick maybe?

**Comment by joeybab3** [comment]
You can try something like this:
via https://stackoverflow.com/questions/17376433/php-imagemagick-invert-color
```
function negateImage($imagePath, $grayOnly, $channel) {
    $imagick = new Imagick(realpath($imagePath));
    $imagick->negateImage($grayOnly, $channel);
    header("Content-Type: image/jpg");
    echo $imagick->getImageBlob();
}
```
It's not exactly the same problem but that `negateImage()` function should invert your barcode from black to white.

**Comment by haivala** [comment]
Why don't you use CSS. Add padding and filter: invert(1)

**Comment by pubi** [comment]
@haivala script is called from the app and we don't have impact on app style - we can provide only image through our api.
@joeybab3 thx for the hint, but we can't get the information about the theme which the user is using

**Comment by casperbakker** [comment]
This library focuses on the generation of the barcode itself. You can add any styling to the image after you got the image from this library.

**Comment by casperbakker** [comment]
Setting the background is now supported in 3.1: https://github.com/picqer/php-barcode-generator/releases/tag/v3.1.0
