### ISSUE TITLE
In PHP 7.4.26 error "Array and string offset access syntax with curly braces is deprecated"

### ISSUE THREAD

**Issue by slavanb** [picqer/php-barcode-generator#147]
In PHP 7.4.26
Array and string offset access syntax with curly braces is deprecated

error
BarcodeGenerator.php
at line 293

in In PHP 7.4.24 -  work norm.

**Comment by joeybab3** [comment]
What version of the library are you using, this has been fixed for a while according to the comments in #98.
It has also been asked before a few times, such as in #105, #112, #114, and #127.
All of those were solved by updating the library so it's likely you have an old version of the library installed.
