### ISSUE TITLE
ITF-14 barcode type not added on to package

### ISSUE THREAD

**Issue by knigherrant** [picqer/php-barcode-generator#151]
Hi,
I see here have commit ITF-14 barcode type, but when i download the package it's not on source, please check and marge it
https://github.com/picqer/php-barcode-generator/pull/137/commits/d8354c1e096ae4cd92fdf864d779bebb95df903a

I have downloaded manual and run, the ITF-14 barcode is like
![image](https://user-images.githubusercontent.com/5679504/165334187-a3257d74-c423-4033-b040-19122859e909.png)

And if i want the barcode with 4 side border like this, how option i can use
![image](https://user-images.githubusercontent.com/5679504/165334453-d35ff5ce-599e-41bb-8cb1-5fc09a21e087.png)

Thanks

**Comment by casperbakker** [comment]
The PR for ITF-14 does not come with any tests. That should be added first, then I can merge it.
