### ISSUE TITLE
Not supporting PHP 8.1.3

### ISSUE THREAD

**Issue by arpan9477** [picqer/php-barcode-generator#156]
My PHP version is 8.1.3. This is not supportive when I am trying to install it by the composer.
Giving this error:
nette/schema v1.2.1 requires php >=7.1 <8.1 -> your php version (8.1.3) does not satisfy that requirement.

**Comment by casperbakker** [comment]
The package `nette/schema` is not used by this library. So it should be something else in your project that needs that package.

With the command `composer why nette/schema` you can find out why that package is included.
