### ISSUE TITLE
Error: Class 'Picqer\Barcode\BarcodeGenerator' not found

### ISSUE THREAD

**Issue by anuj9196** [picqer/php-barcode-generator#16]
I'm using php-barcode-generator in CakePHP framework.
I have installed plugin in vendor directory and using it in my controller

```
require_once(ROOT.'/vendor/picqer/php-barcode-generator/src/BarcodeGeneratorHTML.php');
  public function shippingSlipPrint($order_id = null)
    {
        $generator = new BarcodeGeneratorHTML();
        $barcode = $generator->getBarcode('1234567890', $generator::TYPE_CODE_128);

        $this->set('barcode', $barcode);

    }
```

But this is giving error as

```
Error: Class 'Picqer\Barcode\BarcodeGenerator' not found
File /myapp/vendor/picqer/php-barcode-generator/src/BarcodeGeneratorHTML.php
Line: 6 
```

content of BarcodeGeneratorHTML.php

```
<?php

namespace Picqer\Barcode;

class BarcodeGeneratorHTML extends BarcodeGenerator
{
     .....
    ......
}
```

**Comment by casperbakker** [comment]
Then you also need to require the `ROOT . '/vendor/picqer/php-barcode-generator/src/BarcodeGenerator.php'` file

With Composer we use Autoload, which loads this files automatically.

**Comment by amirvenus** [comment]
I am having a similar issue as I could not use composer.

Please advise

**Comment by casperbakker** [comment]
It is just basic PHP, require/include the proper file before you can use it.

**Comment by amirvenus** [comment]
I fixed the problem by requiring autoload file.

Thanks and keep up the good work
