### ISSUE TITLE
Barcode has no title printed

### ISSUE THREAD

**Issue by yogasukma** [picqer/php-barcode-generator#17]
Hi, thanks for good plugin. 

Anyway, after test to use it, i got the barcode has no title printed. is there possible to create a tittle like regular barcode? see this https://en.wikipedia.org/wiki/Code_128 below the barcode, has 'wikipedia' printed.

**Comment by casperbakker** [comment]
At this moment that is not possible with this project. But you can add it to the image with GD after it is generated. We ourselves add it to the HTML below the image to display the contents.

**Comment by vahidalvandi** [comment]
how i can add with GD for printing ?

**Comment by filiperhiza** [comment]
Yes, it is possible. Just use the file BarcodeGeneratorPNGWithNumber.php
