### ISSUE TITLE
Fatal error: Uncaught Picqer\Barcode\Exceptions\BarcodeException: Neither gd-lib or imagick are installed! in E:\SERVER\htdocs\my_learning\php-barcode-generator-2.2.4\vendor\picqer\php-barcode-generator\src\BarcodeGeneratorPNG.php:22 Stack trace: #0 E:\SERVER\htdocs\my_learning\php-barcode-generator-2.2.4\index.php(7): Picqer\Barcode\BarcodeGeneratorPNG->__construct() #1 {main} thrown in E:\SERVER\htdocs\my_learning\php-barcode-generator-2.2.4\vendor\picqer\php-barcode-generator\src\BarcodeGeneratorPNG.php on line 22

### ISSUE THREAD

**Issue by shafayetnuralam** [picqer/php-barcode-generator#171]
Fatal error: Uncaught Picqer\Barcode\Exceptions\BarcodeException: Neither gd-lib or imagick are installed! in E:\SERVER\htdocs\my_learning\php-barcode-generator-2.2.4\vendor\picqer\php-barcode-generator\src\BarcodeGeneratorPNG.php:22 Stack trace: #0 E:\SERVER\htdocs\my_learning\php-barcode-generator-2.2.4\index.php(7): Picqer\Barcode\BarcodeGeneratorPNG->__construct() #1 {main} thrown in E:\SERVER\htdocs\my_learning\php-barcode-generator-2.2.4\vendor\picqer\php-barcode-generator\src\BarcodeGeneratorPNG.php on line 22

**Comment by shafayetnuralam** [comment]
problem solve

**Comment by darshilworks** [comment]
how?

**Comment by casperbakker** [comment]
Probably by installing GD or Imagick, as the error is saying. Please read the readme.
