### ISSUE TITLE
Inline svg

### ISSUE THREAD

**Issue by webwit** [picqer/php-barcode-generator#173]
Thanks for the great lib! I used it to create an inline svg, but had to strip the <!xml and <!DOCTYPE stuff for that.

No problem, but maybe something like this would be a nice addition in BarcodeGeneratorSVG.php:

- Add param bool $inline = false to getBarcode()
- Only add the <!xml and <!DOCTYPE lines when !$inline

**Comment by casperbakker** [comment]
Thanks for the patience. I fixed it in #198, which will become v3 of this package.
