### ISSUE TITLE
TYPE_EAN_13 Error with 13 numbers

### ISSUE THREAD

**Issue by yakhyomus** [picqer/php-barcode-generator#180]
When i'm trying like this:
`$generator->getBarcode('478000000000', $generator::TYPE_EAN_13)`
with 12 numbers all is good, but when i'm trying with 13 numbers:
`$generator->getBarcode('4780000000000', $generator::TYPE_EAN_13)` i got error:
```
Exception 'Picqer\Barcode\Exceptions\InvalidCheckDigitException' with message '' 

in /app/vendor/picqer/php-barcode-generator/src/Types/TypeEanUpcBase.php:47
```

Whats wrong? Can somebody help me pls? Thank yout!

**Comment by JanMikes** [comment]
Hi, it believe is because `4780000000000` is not valid EAN13 - the exception says it all `InvalidCheckDigitException`

Your `4780000000000` is not valid, check digit is 7, therefore `4780000000007` is valid EAN13.

You can calculate online for example on https://www.gs1.org/services/check-digit-calculator or use some formulas that can be found on internet.

**Comment by casperbakker** [comment]
Yep, JanMikes is right. It is not a valid EAN13 number. You can create a Code128 barcode if you really want 4780000000000 in the barcode. But it is not valid if you want EAN13.

**Comment by xorgxx** [comment]
Hi,  

So, there’s no built-in validation for this? Currently, I’m using Turbo Stream to render a table that includes barcodes. I have a form where users can add a barcode of type **EAN-13**.  

For example:  
- If I enter **2004770027357**, everything works fine.  
- But if I enter 2004770027358, the app crashes, and Turbo Stream fails to render, showing an error. In the debug info, there is no form validation error !!

My question is:  
Should I manually validate the barcode in the controller before committing it to the database, or does the database throw an exception on commit?  

Thanks for your help!

**Comment by JanMikes** [comment]
Well there is validation - if the digit is invalid the `InvalidCheckDigitException` is thrown. You have to implement `try {} catch() {}` on your side to handle cases when the code is invalid.
