### ISSUE TITLE
Image not showing when used text and number, but also showing number.

### ISSUE THREAD

**Issue by obaidul99** [picqer/php-barcode-generator#181]
Hello

Image not showing when used text and number like (W2334RR12), but also showing number like (6432165412).

Here my code::
`ob_clean();
require 'vendor/autoload.php';
use Picqer\Barcode\BarcodeGeneratorPNG;
$text = $_GET['text'];
$price = $_GET['price'];
$generator = new BarcodeGeneratorPNG();
$barcodeImage = $generator->getBarcode($text, $generator::TYPE_CODE_128_C,2,64);
header('Content-Type: image/png');
print $barcodeImage;`

**Comment by obaidul99** [comment]
I am also encode text to base64_encode but also not showing.

**Comment by obaidul99** [comment]
<?php
ob_clean();
require 'vendor/autoload.php';
use Picqer\Barcode\BarcodeGeneratorPNG;
$text = $_GET['text'];
$price = $_GET['price'];
$generator = new BarcodeGeneratorPNG();
$barcodeImage = $generator->getBarcode($text, $generator::TYPE_CODE_128_C,2,64);
header('Content-Type: image/png');
print $barcodeImage;
?>

**Comment by obaidul99** [comment]
`
ob_clean();
require 'vendor/autoload.php';
use Picqer\Barcode\BarcodeGeneratorPNG;
$text = $_GET['text'];
$price = $_GET['price'];
$generator = new BarcodeGeneratorPNG();
$barcodeImage = $generator->getBarcode($text, $generator::TYPE_CODE_128_C,2,64);
header('Content-Type: image/png');
print $barcodeImage;
`

**Comment by obaidul99** [comment]
![Screenshot_1](https://github.com/picqer/php-barcode-generator/assets/30920776/d595882c-426a-417b-933e-2de8d9b34447)

**Comment by obaidul99** [comment]
![Screenshot_3](https://github.com/picqer/php-barcode-generator/assets/30920776/71022de1-7c83-41b1-ad60-11e917def71d)

**Comment by obaidul99** [comment]
Please help

**Comment by casperbakker** [comment]
If you use `TYPE_CODE_128_C` specifically, so version "C", it does not support all characters. See https://barcodewiz.com/activex-control/user-manual/symbologies/code-128-a-b-c-and-auto

If you only use `TYPE_CODE_128`, it will automatically switch between versions A, B and C to get you all the chars you need.
