### ISSUE TITLE
PHP 8.2: fix E_DEPRECATED warning

### ISSUE THREAD

**Issue by 1234ru** [picqer/php-barcode-generator#185]
```php
$generator = new Picqer\Barcode\BarcodeGeneratorSVG();
header("Content-type: image/svg+xml");
echo $generator->getBarcode(123, $generator::TYPE_CODE_128);
```
Currently the code above throws a warning:

> Deprecated: strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in src\Types\TypeCode128.php on line 159

**Comment by casperbakker** [comment]
@1234ru You are probably running an old version of this library, as this is fixed months ago.
