### ISSUE TITLE
Page autosubmit after scan QR code

### ISSUE THREAD

**Issue by mithun8709** [picqer/php-barcode-generator#192]
I scan QR code on my input field , after scanning completed my form page are autosubmit, i want to prevent from autosubmit why ?

**Comment by haivala** [comment]
Your scanner adds the submit after the code scan

**Comment by casperbakker** [comment]
This package does not support QR codes, but maybe you mean a barcode.

@haivala is right, the submit comes from a "return" signal that the hardware barcode scanner gives after the scan. In most cases it can be programmed if a return, tab or nothing is sent after the contents of the barcode itself.

Please check the documentation of the hardware scanner.
