### ISSUE TITLE
Barcodes generated using BarcodeGeneratorDynamicHTML() do not render when printed

### ISSUE THREAD

**Issue by objecttothis** [picqer/php-barcode-generator#194]
In my function I have
```
$generator = new BarcodeGeneratorDynamicHTML();
$barcode_value = $this->get_barcode_value($item, $barcode_config);
return $generator->getBarcode($barcode_value, $barcode_config['barcode_type']);
```
Which properly generates the barcode. I needed to use this method because generating the PNG only allowed me to set a width factor and not an overall width in pixels and I needed all barcodes to have the same width regardless of their content.

The problem is that the barcode does not render when printed.  I tried adding `overflow:visible` to the CSS, but this had no effect. Is there a way to force the print engine to render the `<div>` elements that make up the barcode?

**Comment by casperbakker** [comment]
This is not a problem from this library. This is just HTML/CSS rendering itself.
