### ISSUE TITLE
Code128 don’t work

### ISSUE THREAD

**Issue by RenderWarrior** [picqer/php-barcode-generator#197]
I generated a code128 barcode but it seems it doesn’t be recognized by online tools or barcode real scanners.
Any idea?
Tomorrow i’ll do more tests
thanks!

**Comment by casperbakker** [comment]
Please provide the code you use, and also a picture of the generated barcode. It is very unlikely that you encountered a bug in this library in code128 generation. But maybe you gave it a specific string that it could not handle right.

**Comment by RenderWarrior** [comment]
Hello! Well I deleted everything and I started again and this time it worked.
Probably it was a typo somewhere. Thanks!
