### ISSUE TITLE
Add background and margin on generated barcode

### ISSUE THREAD

**Issue by osflake** [picqer/php-barcode-generator#201]
Hello Mr @casperbakker, 

I have one suggestions, because when I used Your library (very very thanks for that) we found a very big problem in our 1D scanner.

When we present barcode in dark mode (night mode) web browser change background to dark and outer lines are not readable.
![image](https://github.com/picqer/php-barcode-generator/assets/30706575/2d92385e-89f1-4a75-8b1c-f150a814bd2b)

It is possible to add **param** like:
### **$generator->setMargin(10);**
```
$generator = new Picqer\Barcode\BarcodeGeneratorJPG();
$generator->useGd();
$generator->setMargin(10);
$result = $generator->getBarcode($inputValue, $generator::TYPE_CODE_128, 4, 120, $color = array(0, 0, 0));    
header('Content-Type: image/png');
echo $result;
```
or
```
$setMargin = 10;
$result = $generator->getBarcode($inputValue, $generator::TYPE_CODE_128, 4, 120, $color = array(0, 0, 0),$setMargin); 
```   
Its very important issue.

Thank You

**Comment by casperbakker** [comment]
Maybe we will add something after version 3 is launched (see #198), but that will take some time.

In the mean time you can show some white border around the image with HTML/CSS, same way you show the red numbers on top.

**Comment by osflake** [comment]
Hi

I added in HTML/css but web browser removed this

**Comment by casperbakker** [comment]
If you added a background, that is usually ignored when printing. But a white "border" should work while printing.

**Comment by casperbakker** [comment]
Setting the background is now supported in 3.1: https://github.com/picqer/php-barcode-generator/releases/tag/v3.1.0
