### ISSUE TITLE
GTIN14 not working

### ISSUE THREAD

**Issue by 1callservice** [picqer/php-barcode-generator#202]
The readme says to use TYPE_ITF14  for GTIN14 barcodes, but i keep getting fatal error
`Uncaught Error: Undefined class constant 'TYPE_ITF14'`

**Comment by casperbakker** [comment]
@1callservice Can you provide the line of code where you use 'TYPE_ITF14'?

**Comment by 1callservice** [comment]
it seems to work fine when i use composer to install, rather than just including the files.
thanks
