### ISSUE TITLE
Feature Request - Add Attributes variable to SvgRenderer, etc.

### ISSUE THREAD

**Issue by THPAdmin** [picqer/php-barcode-generator#207]
Just a recommendation:

We need an ID attribute added to the SVG html output for javascript purposes, but it's not currently supported.

It would be nice to have an "attributes" variable passed to the "render" method of SVG/HTML generation in files like "Picqer\Barcode\Renderers\SvgRenderer", so that we can define our own attributes, example:

`<svg id="random_id"/>`

The only way to do so is to override the "render" method ourselves. However, that method does like 80 things though! So it will easily break any future updates you make if we do so. It might be further helpful to break up that code into their own methods that can be overridden to give more control over the render process.

Just my 2 cents. Thank you for your hard work in creating this excellent library.

**Comment by casperbakker** [comment]
Can't you get the string of the SVG from the output, and then put in the `id="random_id"` in yourself? Is there something that would prevent that from working?

**Comment by THPAdmin** [comment]
I guess I could do something like this:

```
  use Picqer\Barcode\Renderers\SvgRenderer as renderer;

  $barcode = (new \Picqer\Barcode\Types\TypeCode128())->getBarcode(123);
  $renderer = (new renderer)->setSvgType(renderer::TYPE_SVG_INLINE);
  $svg = $renderer->render($barcode, 135, 20)

  $svg = preg_replace("/<svg.*?>(.*)?<\/svg>/im","$1",$svg); // Remove SVG tags

  print '<svg id="123" width="135" height="20" viewBox="0 0 135 20" version="1.1" xmlns="http://www.w3.org/2000/svg">';
  print $svg;
  print '</svg>';
```
If that's what you mean.

**Comment by casperbakker** [comment]
Yep, like that. Personally I would only add the `id=` portion and maybe str_replace is faster and easier? Seems more future proof than to replace also the other attributes.

```php
$svg = str_replace('<svg ', '<svg id="123" ', $svg, 1);
```

**Comment by THPAdmin** [comment]
Thanks Casper! I didn't even think of doing it that way. 😃
