### ISSUE TITLE
Generating FNC3 character with CODE_128

### ISSUE THREAD

**Issue by ryangriggs** [picqer/php-barcode-generator#24]
Hi, I'm trying to insert the FNC3 character at the beginning of a CODE128 barcode.  I have passed the ASCII 128 character (Ç) in the Value, but it doesn't appear to be correct.  I expect to see this:
[http://is.am/k5](http://is.am/k5)

but instead I get this:
[http://is.am/k6](http://is.am/k6)

What am I doing wrong?

Thanks,
Ryan

**Comment by casperbakker** [comment]
We use char 243 for FNC3 character. So you should use something like:

```php
$content = char(243) . 'restOfBarcode';
```

It that what you tried?

**Comment by benford14** [comment]
@casperbakker I had this same issue trying to recreate the fnc3 character. I am using https://barcode.tec-it.com/en/Code128 and cannot recreate fnc3 properly
