### ISSUE TITLE
Is it possible to display the code below the barcode itself?

### ISSUE THREAD

**Issue by dmarklund** [picqer/php-barcode-generator#27]
As the title states, is it possible?
This is what I have in mind; http://prntscr.com/e8y9ma

The picture is of a EAN13 barcode.

**Comment by stephangroen** [comment]
No. See: https://github.com/picqer/php-barcode-generator/issues/14

**Comment by edmargenesis** [comment]
Yes just locate the BarcodeGeneratorPNG.php file and find the function  createGdImageObject
and update like this. 

Note:  dont forget to add the $barcode parameters on the function

    protected function createGdImageObject(int $width, int $height, $barcode)
    {
        $image = imagecreate($width, $height + 20 );
        $colorBackground = imagecolorallocate($image, 255, 255, 255);

        $font = 12;
        $font_width = ImageFontWidth($font);
        $font_height = ImageFontHeight($font);
        $text_width = $font_width * strlen($barcode);
        $position_center = ceil(($width - $text_width) / 2);

        imagestring($image, $font, $position_center, $height + 5, $barcode, imagecolorallocate($image, 0, 0, 0));

        imagecolortransparent($image, $colorBackground);

        return $image;
    }

and then on the getBarcode() function find createGdImageObject() function and add barcode parameter just like this 
$image = $this->createGdImageObject($width, $height, $barcode);


That's it

and also thank you for this library its helps for me a lot

![image](https://user-images.githubusercontent.com/77605291/144984898-87faeb6a-f5f3-40c6-b4d1-0971852caa14.png)
