### ISSUE TITLE
GS1-128 

### ISSUE THREAD

**Issue by linaocampouam** [picqer/php-barcode-generator#28]
I need to generate a barcode with the standard GS1-128, I had an almost satisfactory result following this post (http://stackoverflow.com/questions/34040995/how-to-properly-generate-a-gs1-128-formerly Barcode-in-tcpdf) but unfortunately the end of the barcode was not the same in comparison to one generated by other system that actually follows the standard and is accepted by our bank.

I expect to see this:
![esperado](https://cloud.githubusercontent.com/assets/25043843/23047200/3b63a0e4-f47c-11e6-9670-cc4df9fdb50c.png)

but instead I get this:
![obtenido](https://cloud.githubusercontent.com/assets/25043843/23047209/40d45bfe-f47c-11e6-89ee-10d8919ecb72.png)

I'm using this code:
`$code = chr(241)."4157709998016989802000105385555480202016103470";`
`$generatorPNG = new Picqer\Barcode\BarcodeGeneratorPNG();`
`echo '<img '`
 `       . 'src="data:image/png;base64,' . base64_encode(`
`                $generatorPNG->getBarcode($code, `
`                        Picqer\Barcode\BarcodeGeneratorPNG::TYPE_CODE_128_C)) `
`        . '"  style="height: 50px; width: 300px ">';   `

I appreciate any help you can give me.

**Comment by casperbakker** [comment]
I also cannot scan the second label, so probably a bug in this library. 

The barcode can be different without it being a problem, because type C can switch between A en B and there are no strict rules when it should switch. So only a different barcode does not mean that it is invalid.

But in this case it looks like it is a invalid result. I cannot fix it right now, but hopefully I find the time in the coming weeks to look in to this.

**Comment by linaocampouam** [comment]
Thanks for answering me.

I have a doubt:
Is it okay to use `$code = chr(241)."4157709998016989802000105385555480202016103470";` for (415)7709998016989(8020)001053855554(8020)2016103470 ?
I read (I do not remember where) that after a data of variable lenght it is necessary to use F1, but I did not know how to enter it.
Could it be also an error in how I define $code?

**Comment by casperbakker** [comment]
That should be the right way.

**Comment by JeisonVM** [comment]
Sorry my english is very bad, You need the ASCII number 29 (GS), that is the separetor GS1-128 (UCC/EAN), this code. That code genera a new FNC1, it is necesary. 
(415)xxxxxx(8020)xxxxxhereCode29(3900)hereCode29xxxxx(96)xxxx
3900 is code money
96 is code date
you can to use CODE128 type A or B.  
ASCII control http://ascii.cl/es/codigos-de-control.htm

GOOD LUCK

**Comment by brianakidd** [comment]
Sorry, I know this is an old issue.  So can I generate a GS1-128 by simply prepending chr(241) and using the 128_C type?

**Comment by GrupoWebex** [comment]
I think gs1-128 codes are not working.
Can anyone get same match from this [online generator](https://barcode.tec-it.com/es/EANUCC128?data=010843659137001711200901211113001)?

 I get it, but with [ayeo library](https://github.com/ayeo/gs1_128)

**Comment by MarioMoncada** [comment]
i  was  trying to solve this issue, and i have done, when a use this set. 
to generate the code a i used millon/barcode . 
chr(241)xxxxxxxxxchr(241)xxxxxxchr(241). when u use the chr(241) it mean that u are using FNC1 separators
chr(241) (415) 1231213233123 (8020) 1234141231331 chr(241) (3900)1231232 chr(241) (96) 11122020
nota: to create the code you have to deleted "()" from  IA . 
IA are represented as 415  ,8020, 3900, 96
