### ISSUE TITLE
Mixup A/B/C in 128 barcodes

### ISSUE THREAD

**Issue by simondaigre** [picqer/php-barcode-generator#29]
Hi,

I need to use A+C modes in same 128 barcode.
I tried to edit current code but it doesnt seems to work.
There is a way to adapt it to get this use case works ?

Thanks

**Comment by casperbakker** [comment]
I don't know how this is possible in the Code128 spec, because something is or in A-mode, or in B-mode. When you use C-mode, it alters between A-mode and B-mode so it creates the smallest code.

If you mean A+B mode, then you use the C-mode.

**Comment by simondaigre** [comment]
Hi,
I have a 13 long digits string. I need to encode the 3 first digits in A and the 10 latests in C.
Its weird, but required by French post office. I dont understand why.

**Comment by casperbakker** [comment]
This library has no support for that kind of requirements. I am sorry.

**Comment by simondaigre** [comment]
Anyway, I still have an issue..
I'm trying to encode 2K12567898709 in C128, but its unreadable.
Here is what I get with your lib:
<img width="419" alt="capture d ecran 2017-03-11 a 17 36 52" src="https://cloud.githubusercontent.com/assets/1218015/23824978/7cbe78c2-0681-11e7-90c6-f0daad866baf.png">

And this one generated with this website works perfect:
http://barcode.tec-it.com/fr/Code128?data=2K12567898709
<img width="283" alt="capture d ecran 2017-03-11 a 17 36 57" src="https://cloud.githubusercontent.com/assets/1218015/23824981/8ba9c364-0681-11e7-9ca9-fa5a9301972e.png">

Any idea of what I do wrong ?
Thanks

Edit: Seems an issue with $widthFactor, i'm trying to set 1.2, when I dont pass this parameter in getBarcode(), barcode is well too.

**Comment by casperbakker** [comment]
Could you post the exact code you are using? Then I will create a separate issue for this one.

**Comment by simondaigre** [comment]
Hi,

```
// include lib for gencode generation
require_once dirname(__FILE__).'/../librairies/php-barcode-generator/BarcodeGenerator.php';
require_once dirname(__FILE__).'/../librairies/php-barcode-generator/BarcodeGeneratorPNG.php';

$generator = new \Picqer\Barcode\BarcodeGeneratorPNG();
$barcode = $generator->getBarcode('2K12567898709', $generator::TYPE_CODE_128, 1.2)
```
Then I pass it to a PDF with base64_encode($barcode);
