### ISSUE TITLE
copyright and license violation

### ISSUE THREAD

**Issue by nicolaasuni** [picqer/php-barcode-generator#3]
This project is using code copied from:
https://github.com/tecnickcom/TCPDF
but all copyright and license terms were removed.
Please immediately delete all the copied code or adapt it to conform the original copyright and license requirements.

Please also note that the code you have copied has now been replaced by another project:
https://github.com/tecnickcom/tc-lib-barcode

Please carefully read the license and act promptly.

**Comment by casperbakker** [comment]
@nicolaasuni You are right. I found some of this code in another project that was MIT licensed, but that was a mess. I create this package to make it more modern and to refactor it bit by bit. I created this lib to get rid of our Zend_Barcode dependency.

After I released this package I found some strange code inconsistencies and Googled for a comment in the code. That is when I found your TCPDF code and that is was released on LGPL and not with MIT, so the other project could never have released it with an MIT license.

It is already on my todo list, but I will soon change the license of this project according to LGPL and make the proper links to your project.

I am sorry for this and it was absolutely not my intention to steal your code and infringe your rights.

**Comment by casperbakker** [comment]
@nicolaasuni I changed the license for this project to LGPLv3 and added the copyright and license information as requested. Is there something I missed or is this issue resolved for you?

**Comment by nicolaasuni** [comment]
All the original copyright notice should be reported in full and your changes should be clearly indicated.
In any case, why don't you use the following project that is derived from the original ones and has tons of bug fixes and improvements?
https://github.com/tecnickcom/tc-lib-barcode

**Comment by casperbakker** [comment]
I am sorry, but the license does not require to indicate all the changes that are being made.

In any case, using your new project is not going to happen anytime soon, because this package with this API is being used in multiple projects now. So stop suggesting that alternative.

If you do not like your code to be modified or forked, use a different license that does not allow forks.

**Comment by nicolaasuni** [comment]
Probably I have not being clear enough.
You have to reinstate the lines that indicate me as the original author as per license.
You are currently violating the license by removing the lines that indicates me as the original author.
Is that clear?

**Comment by casperbakker** [comment]
In the copied file https://github.com/picqer/php-barcode-generator/blob/master/src/BarcodeGenerator.php I already copied your whole header, including noting you as the copyright owner and author. What do you want me to add besides this?
