### ISSUE TITLE
Too much memory is required

### ISSUE THREAD

**Issue by Dmitri10** [picqer/php-barcode-generator#31]
Hi.
I've got a problem with installation. What capacity should I use?
![2017-03-15_17-21-14](https://cloud.githubusercontent.com/assets/2151287/23953459/afe6f298-09a5-11e7-8a8b-c76e73dbc893.png)
I use macOS, laravel and homestead.

**Comment by stephangroen** [comment]
That's a problem unrelated to this package. The lack of memory is an issue from Composer and your server config. Follow the link where Composer suggests the fix and apply that.

https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors

**Comment by Dmitri10** [comment]
Ok. I hadn't this issue before this installation.. If nobody gets the same problem then maybe you're right.
