### ISSUE TITLE
TYPE_UPC_A Fatal error: Uncaught Error

### ISSUE THREAD

**Issue by JTGMAGIC** [picqer/php-barcode-generator#33]
Hi 
I´am trying to create a barcode with TYPE_UPC_A.

```
$generator = new \Picqer\Barcode\BarcodeGeneratorPNG();
echo '<img src="data:image/png;base64,' . base64_encode($generator->getBarcode("081231723897", $generator::TYPE_UPC_A)) . '">';
```

Send me this error:

**Fatal error: Uncaught Error: Class 'Picqer\Barcode\Exceptions\InvalidCheckDigitException' not found in /home/fiesa/public_html/admin/classes/barcode/BarcodeGenerator.php:1509 Stack trace: #0 /home/fiesa/public_html/admin/classes/barcode/BarcodeGenerator.php(152): Picqer\Barcode\BarcodeGenerator->barcode_eanupc('081231723897', 12) #1 /home/fiesa/public_html/admin/classes/barcode/BarcodeGeneratorPNG.php(21): Picqer\Barcode\BarcodeGenerator->getBarcodeData('081231723897', 'UPCA') #2 /home/fiesa/public_html/includes/checkout-review.php(30): Picqer\Barcode\BarcodeGeneratorPNG->getBarcode('081231723897', 'UPCA') #3 /home/fiesa/public_html/index.php(58): include('/home/fiesa/pub...') #4 {main} thrown in /home/fiesa/public_html/classes/barcode/BarcodeGenerator.php on line 1509**

I tried to fix the problem but I could not. Have try it most of TYPES and all look working fine except this one and TYPE_UPC_B. 

Have someone have the same issue? Anyone know how can I fix that ?

**Comment by casperbakker** [comment]
This is because your string is invalid for UPC type barcodes. The last digit has to be a valid check-digit. But for this code it has to be 0 instead of 7.

See: http://www.gs1.org/check-digit-calculator
