### ISSUE TITLE
I want to add label  to the barcode image.

### ISSUE THREAD

**Issue by VPageDevelopment** [picqer/php-barcode-generator#34]
I want to add the label  (which is the barcode number ) of the barcode image at bottom. like the image attached below. I don't know how to do it.. please help me... Thanks in Advance.
![sample](https://cloud.githubusercontent.com/assets/24694419/24400425/03bdd288-13ce-11e7-9bee-86e1e0eb9786.PNG)

**Comment by casperbakker** [comment]
We do not support that, see #14

**Comment by VPageDevelopment** [comment]
thanks for your lightning reply ..
