### ISSUE TITLE
Adding requirement for libgd in README

### ISSUE THREAD

**Issue by jdgwf** [picqer/php-barcode-generator#39]
It'd be wise to add the libgd requirement for PHP in your README.md. It took me a few minutes to debug this (not all installations have it by default - especially if one is using PHP as a quick and dirty CLI scripting environment).

**Comment by casperbakker** [comment]
Hi @jdgwf, I have added it to the readme. Thanks for letting me know.

**Comment by jdgwf** [comment]
Awesome! Thanks for the awesome library!
