### ISSUE TITLE
Parse error: syntax error, unexpected '[' in BarcodeGenerator.php

### ISSUE THREAD

**Issue by cefaloide** [picqer/php-barcode-generator#40]
In localhost works correctly, but when I upload to the server show this error:
**Parse error: syntax error, unexpected '[' in /var/www/vhost/mywebsite.com/vendor/picqer/php-barcode-generator/src/BarcodeGenerator.php on line 228** 

I guess that the problem is the PHP version:
-Localhost PHP Version 5.6.7
-Online Server PHP Version 5.3.3

**Comment by stephangroen** [comment]
Yes, this package requires at least PHP 5.4. Of course 5.6 or 7 are recommended.
