### ISSUE TITLE
Is pdf417 suppported?

### ISSUE THREAD

**Issue by drnasin** [picqer/php-barcode-generator#43]
Hello there, I'm looking for a generator that can generate boarding pass barcodes in pdf417 format. Can this library do that? Thank you!

**Comment by stephangroen** [comment]
Only codes in the list in the README are supported: https://github.com/picqer/php-barcode-generator#accepted-types

**Comment by stephangroen** [comment]
https://packagist.org/search/?q=pdf417 :)
