### ISSUE TITLE
How to save the generated image

### ISSUE THREAD

**Issue by yassersharaf** [picqer/php-barcode-generator#44]
Hi
I can generate the image in the html page but how to save it as an image

    echo '<img src="data:image/png;base64,' . base64_encode($generator->getBarcode('081231723897', $generator::TYPE_CODE_128)) . '">';

**Comment by casperbakker** [comment]
To save the resulting image to disk with PHP:

```php
file_put_contents('barcode.jpg', $generator->getBarcode('081231723897', $generator::TYPE_CODE_128));
```
