### ISSUE TITLE
Detect barcode type

### ISSUE THREAD

**Issue by gastongr** [picqer/php-barcode-generator#47]
Thanks for the great library!
Just a small suggestion, there are times when you don't know the barcode type in advance (some products use EAN some UPC), so it would be usefull to have an autodetection feature when type is not provided.

Regards

**Comment by casperbakker** [comment]
Thanks @gastongr 

Could you give me a concrete example of the situation?

**Comment by gastongr** [comment]
For example in retail, some articles might have a UPC barcode and some EAN.
If you had to list all the articles along with the corresponding barcode image, it would be good to be able to use 
```
foreach ($articles as $article) {
    echo $generator->getBarcode($article->barcode);
}
```
That is, call `getBarcode()` without knowing the barcode type in advance.

**Comment by gastongr** [comment]
Maybe the autodetection could be taken from https://github.com/violuke/php-barcodes, wich detects the barcode type given a barcode string. Just a suggestion though.

**Comment by casperbakker** [comment]
Well, there are a lot of options with this library in barcode types. A lot of strings can be handled by 30-50% of all methods in this package.

You only want the distinction between UPC and EAN, which is probably a simple if statement. I don't think it is something that this library should do at this moment.

Will keep this use case in mind though. Thanks for your explanation.
