### ISSUE TITLE
array definition

### ISSUE THREAD

**Issue by shimbala** [picqer/php-barcode-generator#50]
HI, can you please change all array definitions [] to array().
php v5.3.29 throws error.

**Comment by stephangroen** [comment]
Hi @shimbala, we cannot. This package requires PHP >= 5.4.0.

**Comment by shimbala** [comment]
OK, but it works without any problems on 5.3.29

**Comment by stephangroen** [comment]
PHP 5.3 has gone EOL 3 years, 1 month ago. The short array syntax make for more clearer code. If you really need it on 5.3.29 feel free to create a fork and make the necessary changes :)
