### ISSUE TITLE
Problems with testing

### ISSUE THREAD

**Issue by ZaakaJarimbo** [picqer/php-barcode-generator#54]
I have tried to install the barcode library in to my setup, (first time using composer etc) and I am getting the following:
 '
`Fatal error: Uncaught Error: Class 'picqer\barcode\BarcodeGeneratorHTML' not found in C:\wamp64\www\bc\test.php:13 Stack trace: #0 {main} thrown in C:\wamp64\www\bc\test.php on line 13'
`

Do i need to place the barcode library in a certain location?

**Comment by casperbakker** [comment]
It is a bug in your own code. You are probably not using capitals right in the class name, class names are case sensitive.
