### ISSUE TITLE
Display code in the image

### ISSUE THREAD

**Issue by eft0stuff** [picqer/php-barcode-generator#56]
It's there any way to display the code below the generated image ?

**Comment by casperbakker** [comment]
Nope.

See #25 #27 #34 and #46

**Comment by filiperhiza** [comment]
Yes, it is possible. Just use the file BarcodeGeneratorPNGWithNumber.php

**Comment by MULLAINATHAN** [comment]
Where to find BarcodeGeneratorPNGWithNumber.php. I can't get any files. Please help me. Thanks in advance.

**Comment by filiperhiza** [comment]
Hello :)
In my case this is in the library folder.

`<?php

namespace Picqer\Barcode;

use Picqer\Barcode\Exceptions\BarcodeException;

class BarcodeGeneratorPNG extends BarcodeGenerator
{

    /**
     * Return a PNG image representation of barcode (requires GD or Imagick library).
     *
     * @param string $code code to print
     * @param string $type type of barcode:
     * @param int $widthFactor Width of a single bar element in pixels.
     * @param int $totalHeight Height of a single bar element in pixels.
     * @param array $color RGB (0-255) foreground color for bar elements (background is transparent).
     * @return string image data or false in case of error.
     * @public
     */
    public function getBarcode($code, $type, $widthFactor = 2, $totalHeight = 30, $color = array(0, 0, 0))
    {
        $barcodeData = $this->getBarcodeData($code, $type);

        // calculate image size
        $width = ($barcodeData['maxWidth'] * $widthFactor);
        $height = $totalHeight;

        if (function_exists('imagecreate')) {
            // GD library
            $imagick = false;
            $png = imagecreate($width, $height + 20); // +20 (+)
            $colorBackground = imagecolorallocate($png, 255, 255, 255);
            imagecolortransparent($png, $colorBackground);
            $colorForeground = imagecolorallocate($png, $color[0], $color[1], $color[2]);
        } elseif (extension_loaded('imagick')) {
            $imagick = true;
            $colorForeground = new \imagickpixel('rgb(' . $color[0] . ',' . $color[1] . ',' . $color[2] . ')');
            $png = new \Imagick();
            $png->newImage($width, $height + 20, 'none', 'png'); // +20 (+)
            $imageMagickObject = new \imagickdraw();
            $imageMagickObject->setFillColor($colorForeground);
        } else {
            throw new BarcodeException('Neither gd-lib or imagick are installed!');
        }

        // print bars
        $positionHorizontal = 0;
        foreach ($barcodeData['bars'] as $bar) {
            $bw = round(($bar['width'] * $widthFactor), 3);
            $bh = round(($bar['height'] * $totalHeight / $barcodeData['maxHeight']), 3);
            if ($bar['drawBar']) {
                $y = round(($bar['positionVertical'] * $totalHeight / $barcodeData['maxHeight']), 3);
                // draw a vertical bar
                if ($imagick && isset($imageMagickObject)) {
                    $imageMagickObject->rectangle($positionHorizontal, $y, ($positionHorizontal + $bw), ($y + $bh));
                } else {
                    imagefilledrectangle($png, $positionHorizontal, $y, ($positionHorizontal + $bw) - 1, ($y + $bh),
                        $colorForeground);
                }
            }
            $positionHorizontal += $bw;
        }

    if ($imagick && isset($imageMagickObject)) {
        $draw = new ImagickDraw();
        $draw->setFillColor('black');

        /* Font properties */
        $draw->setFont('Bookman-DemiItalic');
        $draw->setFontSize(1);

        // Write the barcode's code, change $code to write other text
        $imageMagickObject->annotateImage($draw, 0, $height + 5, 0, $code);
    }

    else
    {
        // Detect center position
        $font = 1;
        $font_width = ImageFontWidth($font);
        $font_height = ImageFontHeight($font);
        $text_width = $font_width * strlen($code);
        $position_center = ceil(($width - $text_width) / 2);

        // Default font
        // Write the barcode's code, change $code to write other text
        imagestring($png, $font, $position_center, $height + 5, $code, imagecolorallocate($png, 0, 0, 0));

        // For custom font specify path to font file
        /*$fontPath = '..\font.ttf';
        imagettftext($png, 12, 0, $position_center, $height + 5, imagecolorallocate($png, 0, 0, 0), $fontPath, $code);*/
    }

        ob_start();
        if ($imagick && isset($imageMagickObject)) {
            $png->drawImage($imageMagickObject);
            echo $png;
        } else {
            imagepng($png);
            imagedestroy($png);
        }
        $image = ob_get_clean();

        return $image;
    }
}`

**Comment by MULLAINATHAN** [comment]
Thank you so much. It's working good :+1:

**Comment by mr-nit** [comment]
> Hello :)
> In my case this is in the library folder.
> 
> `<?php
> 
> namespace Picqer\Barcode;
> 
> use Picqer\Barcode\Exceptions\BarcodeException;
> 
> class BarcodeGeneratorPNG extends BarcodeGenerator
> {
> 
> ```
> /**
>  * Return a PNG image representation of barcode (requires GD or Imagick library).
>  *
>  * @param string $code code to print
>  * @param string $type type of barcode:
>  * @param int $widthFactor Width of a single bar element in pixels.
>  * @param int $totalHeight Height of a single bar element in pixels.
>  * @param array $color RGB (0-255) foreground color for bar elements (background is transparent).
>  * @return string image data or false in case of error.
>  * @public
>  */
> public function getBarcode($code, $type, $widthFactor = 2, $totalHeight = 30, $color = array(0, 0, 0))
> {
>     $barcodeData = $this->getBarcodeData($code, $type);
> 
>     // calculate image size
>     $width = ($barcodeData['maxWidth'] * $widthFactor);
>     $height = $totalHeight;
> 
>     if (function_exists('imagecreate')) {
>         // GD library
>         $imagick = false;
>         $png = imagecreate($width, $height + 20); // +20 (+)
>         $colorBackground = imagecolorallocate($png, 255, 255, 255);
>         imagecolortransparent($png, $colorBackground);
>         $colorForeground = imagecolorallocate($png, $color[0], $color[1], $color[2]);
>     } elseif (extension_loaded('imagick')) {
>         $imagick = true;
>         $colorForeground = new \imagickpixel('rgb(' . $color[0] . ',' . $color[1] . ',' . $color[2] . ')');
>         $png = new \Imagick();
>         $png->newImage($width, $height + 20, 'none', 'png'); // +20 (+)
>         $imageMagickObject = new \imagickdraw();
>         $imageMagickObject->setFillColor($colorForeground);
>     } else {
>         throw new BarcodeException('Neither gd-lib or imagick are installed!');
>     }
> 
>     // print bars
>     $positionHorizontal = 0;
>     foreach ($barcodeData['bars'] as $bar) {
>         $bw = round(($bar['width'] * $widthFactor), 3);
>         $bh = round(($bar['height'] * $totalHeight / $barcodeData['maxHeight']), 3);
>         if ($bar['drawBar']) {
>             $y = round(($bar['positionVertical'] * $totalHeight / $barcodeData['maxHeight']), 3);
>             // draw a vertical bar
>             if ($imagick && isset($imageMagickObject)) {
>                 $imageMagickObject->rectangle($positionHorizontal, $y, ($positionHorizontal + $bw), ($y + $bh));
>             } else {
>                 imagefilledrectangle($png, $positionHorizontal, $y, ($positionHorizontal + $bw) - 1, ($y + $bh),
>                     $colorForeground);
>             }
>         }
>         $positionHorizontal += $bw;
>     }
> 
> if ($imagick && isset($imageMagickObject)) {
>     $draw = new ImagickDraw();
>     $draw->setFillColor('black');
> 
>     /* Font properties */
>     $draw->setFont('Bookman-DemiItalic');
>     $draw->setFontSize(1);
> 
>     // Write the barcode's code, change $code to write other text
>     $imageMagickObject->annotateImage($draw, 0, $height + 5, 0, $code);
> }
> 
> else
> {
>     // Detect center position
>     $font = 1;
>     $font_width = ImageFontWidth($font);
>     $font_height = ImageFontHeight($font);
>     $text_width = $font_width * strlen($code);
>     $position_center = ceil(($width - $text_width) / 2);
> 
>     // Default font
>     // Write the barcode's code, change $code to write other text
>     imagestring($png, $font, $position_center, $height + 5, $code, imagecolorallocate($png, 0, 0, 0));
> 
>     // For custom font specify path to font file
>     /*$fontPath = '..\font.ttf';
>     imagettftext($png, 12, 0, $position_center, $height + 5, imagecolorallocate($png, 0, 0, 0), $fontPath, $code);*/
> }
> 
>     ob_start();
>     if ($imagick && isset($imageMagickObject)) {
>         $png->drawImage($imageMagickObject);
>         echo $png;
>     } else {
>         imagepng($png);
>         imagedestroy($png);
>     }
>     $image = ob_get_clean();
> 
>     return $image;
> }
> ```
> 
> }`

Thank you! it's work
