### ISSUE TITLE
Base 64 encoding

### ISSUE THREAD

**Issue by sulemankhan447** [picqer/php-barcode-generator#57]
i am using this library for printing barcode in receipt but base64_encode in image tag makes data very big which alternately makes barcode big which prints only half of receipt paper as barcode size gets bigger than paper size
Please help how to fix ?

**Comment by casperbakker** [comment]
Use css styles on the image tag to make the size of the barcode image exactly like you want it to appear. I always generate the image bigger then needed, to ensure proper DPI while printing.
