### ISSUE TITLE
Need more examples

### ISSUE THREAD

**Issue by greatontime** [picqer/php-barcode-generator#60]
Hi I used your plugin it's very good. But I don't understand some variables.
Can you give me some example how to used this?
`The ->getBarcode() routine accepts the following:

$code Data for the barcode
$type Type of barcode, use the constants defined in the class
$widthFactor Width is based on the length of the data, with this factor you can make the barcode bars wider than default
$totalHeight The total height of the barcode
$color Hex code of the foreground color`

Many Thanks

**Comment by casperbakker** [comment]
Thanls. The parameters are explained there pretty well. But to 'understand' them better, just change the parameters a bit and see what changes in the output.
