### ISSUE TITLE
A non-numeric value encountered.

### ISSUE THREAD

**Issue by n0kit31** [picqer/php-barcode-generator#62]
Warning: A non-numeric value encountered in vendor/picqer/php-barcode-generator/src/BarcodeGenerator.php on line 1489

**Comment by casperbakker** [comment]
If you do not give any information, I will not look into issues.

**Comment by n0kit31** [comment]
What kind of information do you need? Above warning happens when bar code is being generated (EAN13)
The Ean is: 5900511161717
PHP (fpm) version is 7.1.4
