### ISSUE TITLE
EAN-18 / NVE / SSCC-18

### ISSUE THREAD

**Issue by igarpoor** [picqer/php-barcode-generator#63]
Hi, i need to create EAN18, do you think we can adapt the barcode_eanupc function to manage this codes?
Thanks

**Comment by casperbakker** [comment]
We do not have explicit support for EAN18. I also do not have any experience with those codes. You can try if it is good enough, but I guess there needs to be some specific handling of the (00) prefixes and maybe more.

**Comment by joeybab3** [comment]
@casperbakker I am looking to make SSCC-18 barcodes as well, is there anywhere you could point me to try and adapt this library to be able to generate them?
