### ISSUE TITLE
how to call formats from array 

### ISSUE THREAD

**Issue by diekaines** [picqer/php-barcode-generator#64]
i have an array with some barcode types that this library supports and want to create the images .

trying 

```
$barcode_value = '123456' ;

foreach($arr as $single){
echo '<img src="data:image/png;base64,' . base64_encode($generator->getBarcode($barcode_value,$generator::$single  )) . '">';		
}
```

gives me errors 

Any help ?

Thank you

**Comment by casperbakker** [comment]
Without the error messages we cannot help, and it is probably a mistake in your own code rather then in this library.
