### ISSUE TITLE
SVG: viewBox attribute

### ISSUE THREAD

**Issue by cuchac** [picqer/php-barcode-generator#66]
Hi,
SVG images without viewBox attribute cannot be scaled or fitted - for example "scale barcode to fit this DIV element"
By setting attribute viewBox containing width and height already present on svg attribute, it enables scaling and fitting of generted barcode image.

```
<svg width="268" height="70" viewBox="0 0 268 70">
```

Would you accept a merge request for this?

**Comment by casperbakker** [comment]
If it does not have any downsides to add it, I see no problem in adding that. A PR for that is welcome.

**Comment by cuchac** [comment]
Hi,

see #68

**Comment by casperbakker** [comment]
Thanks. Just released v0.3 with this addition.
