### ISSUE TITLE
Class Structure is not PSR-4 Compatible.

### ISSUE THREAD

**Issue by mrunwal** [picqer/php-barcode-generator#67]
This structure is not properly compatible with [psr4](https://www.php-fig.org/psr/psr-4/) so its getting difficult with accessing namespaces and rework needed on this.

**Comment by casperbakker** [comment]
What do you think is wrong? Looks to me like it is a valid PSR-4 structure. We use it only in PSR-4 projects and is working fine with the file naming.

**Comment by mrunwal** [comment]
Ya...its resolved. It was just forward slash works for me.
Looks valid ps4. Earlier I was expected folder structure but things looks okay as of now.
It working.

**Comment by casperbakker** [comment]
Cool
