### ISSUE TITLE
Need Make decomposition of BarcodeGenerator.php

### ISSUE THREAD

**Issue by RomanKorolev** [picqer/php-barcode-generator#72]
Use base technics of OOP:
1) make bar-code base class base_barcode with common methods (i don't know exactly which one)
2) create inherited  from base_barcode clases like:
a) barcode_EAN_13
b) barcode_CODE_128
c) ...

and use it  like this:

$code_engine = new barcode_EAN_13();
$generatorSVG = new Picqer\Barcode\BarcodeGeneratorSVG( $code_engine );
$generatorSVG->generate('081231723897');

**Comment by RomanKorolev** [comment]
OR use other method

$generatorSVG = new Picqer\Barcode\BarcodeGeneratorSVG( $generatorSVG::TYPE_EAN_13 );
$generatorSVG->generate('081231723897');

**Comment by casperbakker** [comment]
Yes, we are building this in #91. Thanks for your concern.

This was first a rip from the TCPDF project, where to code was really bad. Bit by bit we are improving the original code to better fix possible bugs and make the code quicker.
