### ISSUE TITLE
Error in last bar of code128 when widthFactor is 1

### ISSUE THREAD

**Issue by PuustKuusk** [picqer/php-barcode-generator#74]
```
$generator = new \Picqer\Barcode\BarcodeGeneratorPNG();
$generator->getBarcode('JJFI63195820019761766', $generator::TYPE_CODE_128, $widthFactor = 1);
```

Last black bar is too thick if $widthFactor is 1.
Width of 2 or more seems to work.

**Comment by PuustKuusk** [comment]
I have fixed it for me changing line containing
  if ($bar['drawBar'])
to
  if ($bar['drawBar'] && $bar['width'])

in files BarcodeGeneratorPNG.php and BarcodeGeneratorJPG.php

**Comment by casperbakker** [comment]
I don't see any changes in the output with a width of 1 and 2, and with the change to add your bar width check.

This is current version with a width of 1:
![test](https://user-images.githubusercontent.com/886975/71723868-856b5a80-2e2e-11ea-80a4-85273f27a614.png)

This is with your extra check and a width of 1:
![test2](https://user-images.githubusercontent.com/886975/71723889-99af5780-2e2e-11ea-82a9-4730fd0af09e.png)

This is current version with a width of 2:
![test4](https://user-images.githubusercontent.com/886975/71723929-b8155300-2e2e-11ea-90f0-4cdca637a1ae.png)

This is with your extra check and a width of 2:
![test3](https://user-images.githubusercontent.com/886975/71723950-c06d8e00-2e2e-11ea-8bbb-203fd501ddfb.png)

If you still see this problem, maybe you could add the image you get as a result?

**Comment by PuustKuusk** [comment]
3303ba1 Fixes the problem. Thank You.
