### ISSUE TITLE
I don't see number under my EAN 13 barcode

### ISSUE THREAD

**Issue by er-ko** [picqer/php-barcode-generator#78]
Hi i don't know how to set numbers under the barcode. I need to generate barcode of type EAN 13 with numbers? Can anyone help me?

Thank you so much.

**Comment by joeybab3** [comment]
This library just generates the barcode, if you want the number, just output it into html or use php to add it to your image file.

**Comment by donatiss** [comment]
could you please explain how to do that?

**Comment by slokhorst** [comment]
@joeybab3 the thing with EAN-13 is that the number is integrated in the barcode in a special way:

![EAN-13 example](https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/EAN13.svg/1200px-EAN13.svg.png)

**Comment by casperbakker** [comment]
That is not officially part of the 'barcode'. It is just some fancy makeup. We do not support printing characters below the barcode in this package.

**Comment by slokhorst** [comment]
I wouldn't call it arbitrary "fancy makeup", as GS1 specifies it pretty strictly in the [GS1 General Specifications](https://www.gs1.org/docs/barcodes/GS1_General_Specifications.pdf) (section 5.2.5 Human readable interpretation):

> All the encoded digits for EAN-13, UPC-A, and EAN-8 barcodes, and the add-on symbols SHALL be
shown in human readable interpretation form. 

> The minimum space between the top of the digits and the bottom of the bars (dark bars) SHALL be
0.5X. Normally the minimum is one module, which is close enough to keep the human readable
interpretation associated with the symbol.

> In the EAN-13, the leftmost digit, which is encoded by variable parity, is printed to the left of the
start guard pattern in line with the other digits.

As author of this library, you are of course free to ignore this, but it unfortunately rules out using the library for any official commercial purposes.

**Comment by casperbakker** [comment]
Okay, then it is fair to say that it should be part of a EAN or UPC barcode. This library focuses on the 'bars' part of 'barcodes'. You can add any tekst you want below the resulting image. 

Allowing to add text to the barcode will come with a lot of extra parameters, because people want to have there own fonts, font styles, font sizes, letter spacing and so forth. It will also not be parsed/presented the same way in the HTML and SVG generators as with the JPG and PNG generators.

This library fixes the hard problem: transforming your text to a barcode. Everything else you can add easily yourself later.

I am working on separating the generators and the renderers more from each other, which will make it easier for people to add there own renderer that also adds the text in the preferred font and style.

**Comment by falvarezh90** [comment]
My fast solution for this with Imagick (isn't perfect, but it can be improved):

```php       
        $code = "081231723897";
        $generator = new BarcodeGeneratorPNG();
        
        // Image with bar code
        $barCodeImg = $generator->getBarcode($code, $generator::TYPE_CODE_128);
        $imagick = new \Imagick();
        $imagick->readImageBlob($barCodeImg);

        // image with text code
        $imagick->newImage($imagick->getImageWidth(), 20, 'none');
        $draw = new \ImagickDraw();
        $draw->setFillColor('black');
        $draw->setFont('Bookman-Demi');
        $draw->setFontSize(15);
        $imagick->annotateImage($draw, 45, 15, 0, $code);

        // Vertical concatenation (barcode and textcode)
        $imagick->resetIterator();
        $imagick = $imagick->appendImages(true);

        // format and generate base64 image
        $imagick->setImageFormat("png");        
        $barCodeImg = $imagick->getImageBlob();
        return base64_encode($barCodeImg);
```

**Result**

![image(5)](https://user-images.githubusercontent.com/18221884/75283889-7384b300-57f2-11ea-9c79-92516284df72.png)

**Comment by MrZmurf** [comment]
Here is my quick-fix to add numbers to EAN. UPC and Code 128, it might have lot's of bugs but it works for me and my barcode reader :)

        <?php
        require('vendor/autoload.php');
        
        # Test EAN
        $type='EAN';
        $barcode='7039560000390';
        
        # Test UPC
        //$type= 'UPC';
        //$barcode='812208028942';

        # Test Code  128
        //$type='Code 128';
        //$barcode='Some text';

        $generator = new Picqer\Barcode\BarcodeGeneratorPNG();
        if($type == 'EAN') {
                $barCodeImg = $generator->getBarcode($barcode, $generator::TYPE_EAN_13, 3, 120);

                $imagick = new \Imagick();
                $imagick->readImageBlob($barCodeImg);
                $imagick->setImageBackgroundColor('white');

                # Make room for text
                $imagick->extentImage($imagick->getImageWidth()+25,$imagick->getImageHeight()+15,-25,0);

                # Draw barcode numbers on image
                $draw = new \ImagickDraw();
                $draw->setStrokeWidth(1);
                $draw->setFillColor('black');
                $draw->setFont('Noto-Mono');
                $draw->setTextUnderColor('white');
                $draw->setFontSize(35);

                preg_match('/^(\d)(\d{6})(\d{6})$/',$barcode,$parts);
                $imagick->annotateImage($draw, 0, 135, 0, $parts['1']);
                $imagick->annotateImage($draw, 35, 135, 0, $parts['2']);
                $imagick->annotateImage($draw, 174, 135, 0, $parts['3']);
                $imagick->resetIterator();
                $imagick = $imagick->appendImages(true);

                $imagick->setImageFormat("png");
                $barCodeImg = $imagick->getImageBlob();
        } else if($type == 'UPC') {
                $barCodeImg = $generator->getBarcode($barcode, $generator::TYPE_UPC_A, 3, 120);
                $imagick = new \Imagick();
                $imagick->readImageBlob($barCodeImg);
                $imagick->setImageBackgroundColor('white');

                # Make room for text
                $imagick->extentImage($imagick->getImageWidth()+50,$imagick->getImageHeight()+15,-25,0);

                # Draw barcode numbers on image
                $draw = new \ImagickDraw();
                $draw->setStrokeWidth(1);
                $draw->setFillColor('black');
                $draw->setFont('Noto-Mono');
                $draw->setTextUnderColor('white');
                $draw->setFontSize(30);

                preg_match('/^(\d)(\d{5})(\d{5})(\d)$/',$barcode,$parts);
                $imagick->annotateImage($draw, 5, 135, 0, $parts[1]);
                $imagick->annotateImage($draw, 35, 135, 0, " ".$parts[2]." ");
                $imagick->annotateImage($draw, 173, 135, 0, " ".$parts[3]." ");
                $imagick->annotateImage($draw, 311, 135, 0, $parts[4]);
                $imagick->resetIterator();
                $imagick = $imagick->appendImages(true);

                $imagick->setImageFormat("png");
                $barCodeImg = $imagick->getImageBlob();
        } else {
                $barCodeImg = $generator->getBarcode($barcode, $generator::TYPE_CODE_128, 3, 120);
                $imagick = new \Imagick();
                $imagick->readImageBlob($barCodeImg);
                $imagick->setImageBackgroundColor('white');

                # Make room for text
                $imagick->extentImage($imagick->getImageWidth(),$imagick->getImageHeight()+15,0,18);
        
                # Draw barcode numbers on image
                $draw = new \ImagickDraw();
                $draw->setFillColor('black');
                $draw->setFont('Noto-Mono');
                $draw->setTextUnderColor('white');
                $draw->setFontSize(28);
                $draw->setStrokeWidth(1);
                $draw->annotation(0, 51, $barcode);
                $imagick->setGravity(Imagick::GRAVITY_CENTER);
                $imagick->drawImage($draw);
                $imagick->resetIterator();
                $imagick = $imagick->appendImages(true);

                $imagick->setImageFormat("png");
                $barCodeImg = $imagick->getImageBlob();
        }
        echo '<img src="data:image/png;base64,'.base64_encode($barCodeImg).'">';
        ?>

**Result EAN:** 
![ean](https://user-images.githubusercontent.com/93130861/138690496-2ff70ef2-6d2a-4543-a6a7-05c4d77eb8a0.png)

**Result UPC:**
![upc](https://user-images.githubusercontent.com/93130861/138690505-a9560bfa-1e8a-443c-bc9e-44a5fd1d5f8d.png)

**Result Code 128:**
![code128](https://user-images.githubusercontent.com/93130861/138690515-82a28954-63c1-4a9c-a035-fff8d0e66df5.png)

**Comment by cottton** [comment]
Just another easy example with code added below center:

    $code = 'foo;bar;baz;123';
    
    $generator = new \Picqer\Barcode\BarcodeGeneratorJPG();
    $image = $generator->getBarcode($code, $generator::TYPE_CODE_128);
    
    $fontSize = 15;
    $imagick = new \Imagick();
    $imagick->readImageBlob($image);
    $imagick->newImage($imagick->getImageWidth(), $fontSize + 1, 'white');
    $draw = new \ImagickDraw();
    $draw->setFillColor(new \ImagickPixel('black'));
    $draw->setFont('Noto-Mono');
    $draw->setFontSize($fontSize);
    $draw->annotation(0, 0, $code);
    $imagick->setGravity(\Imagick::GRAVITY_CENTER);
    $imagick->drawImage($draw);
    $imagick->resetIterator();
    $imagick = $imagick->appendImages(true);
    $imagick->setImageFormat('png');
    $image = $imagick->getImageBlob();
    
    $imageB64 = base64_encode($image);
