### ISSUE TITLE
2D barcode support like QR Code, Datamatrix, PDF 417, Aztec etc?

### ISSUE THREAD

**Issue by ChangePlaces** [picqer/php-barcode-generator#83]
Do you plan on support 2D barcodes? I see over two years ago you said they weren't being supported, but they're everywhere nowadays and would ask you to reconsider

**Comment by memtech3** [comment]
+1

**Comment by lossendae** [comment]
There are other library who handle 2D barcodes really well. 

I'm not sure adding more options would be the right choice here. In the sense that more options also means more potential bugs and more maintenance.

**Comment by ChangePlaces** [comment]
those other libraries handle 1d barcodes "really well" too. I'm using them now and have no use for this now! Thanks
