### ISSUE TITLE
Orientation option

### ISSUE THREAD

**Issue by jomofcw** [picqer/php-barcode-generator#86]
Hello !

Thanks for the work.
It would be nice if we could have an "orientation" option ("horizontal" or "vertical") .
Is it possible, please ?

**Comment by Mr-TOA** [comment]
Hi Jomo,
you can use CSS for that:
```
.vertical_barcode {
     transform: rotate(-90deg);
     transform-origin: right, top;
     -ms-transform: rotate(-90deg);
     -ms-transform-origin:right, top;
     -webkit-transform: rotate(-90deg);
     -webkit-transform-origin:right, top;
}
```

**Comment by jomofcw** [comment]
Hello,

Thanks for your answer.
I've tried this, but I have to put it in a PDF, using mPDF, and it doesn't support the "transform" CSS property, sadly. So curently I use JPG barcode and an image modificator to rotate it. Would be nicer with an orientation option.

**Comment by casperbakker** [comment]
> So curently I use JPG barcode and an image modificator to rotate it. Would be nicer with an orientation option.

I think that is a fine solution for your use case.
