### ISSUE TITLE
README should specify minimum PHP version.

### ISSUE THREAD

**Issue by shivanraptor** [picqer/php-barcode-generator#9]
Running the library on PHP 5.3 will raise:

> Parse error: syntax error, unexpected '[' in /path/to/project/vendor/picqer/php-barcode-generator/src/BarcodeGenerator.php on line 228

Line 228: `$chr = [];`

which is short array syntax introduced in PHP 5.4: http://php.net/manual/en/migration54.new-features.php

Such shortcode is unnecessary and reduce version compatibility. Can you change back to:

```
$chr = array();
```

p.s. multiple `[]` detected in the `BarcodeGenerator.php`

**Comment by stephangroen** [comment]
The composer.json file for this package requires php 5.4+.

``` json
    "require": {
        "php": ">=5.4.0"
    }
```

The package will not be made php 5.3 compatible, because this version went EOL on 14 Aug 2014.
