### ISSUE TITLE
generator->getBarcode() returns image resource

### ISSUE THREAD

**Issue by ThePureCC** [picqer/php-barcode-generator#93]
Hi,

I plan on add the text to the generated image. Currently it the getBarcode() function generates a text file to save to a jpg/png file. I'm wondering if its possible for the function to output the image as an image resource for me to further manipulate it in PHP instead of outputting it to a file and read it to save some disk IO sources.

**Comment by casperbakker** [comment]
With the new 2.0 version, you can extend the BarcodeGeneratorPNG class and overwrite the generateGdImage, if you force the use of GD. There you have control over the resource before it is rendered.

I plan on separating the generators and renderers so we can support more type of renderers, including one that adds text below the image. But for now, the above way should work.
