### ISSUE TITLE
Special character in TYPE_CODE_128

### ISSUE THREAD

**Issue by KenzoLaw** [picqer/php-barcode-generator#95]
Hello, 

when I running this code by inserting the value consists of special characters such as ( &, <, >, ) between numbers 
$generator = new Picqer\Barcode\BarcodeGeneratorPNG();
echo '<img src="data:image/png;base64,' . base64_encode($generator->getBarcode('12&13', $generator::TYPE_CODE_128)) . '">';

![image](https://user-images.githubusercontent.com/13806253/72519768-072da000-3893-11ea-866d-9d2177a12b51.png)

The result able to generate with the barcode however when I do scanning, the value display comes out on with encoded `12&amp;13` but not '12&13'.

How should I solve this problem? Any helps? Thank you.

**Comment by casperbakker** [comment]
Hi @KenzoLaw ,

I think you made an error somewhere before feeding the string to the barcode generator. When I try to build `12&13` as a Code 128, I get the following code:

![Screenshot 2020-01-28 at 13 57 44](https://user-images.githubusercontent.com/886975/73265921-2a7f1600-41d6-11ea-8f38-f18ce3d79c7e.png)

That is correct. The Code 128 generator itself give me that it used the chars: 17, 18, 6, 17, 19. That is also correct. Char 6 is the ampersand.
