### ISSUE TITLE
Deprecation warning in php 7.4

### ISSUE THREAD

**Issue by wa1kb0y** [picqer/php-barcode-generator#97]
In php 7.4 
Array and string offset access syntax with curly braces is deprecated

![Снимок экрана 2020-03-31 в 22 44 11](https://user-images.githubusercontent.com/5966172/78068534-3c7d6080-73a1-11ea-9490-285fb83fa4bd.png)

Thank you for great extension!

**Comment by Hendri4O4** [comment]
Same In PHP 7.4
Message: Array and string offset access syntax with curly braces is deprecated.

![image](https://user-images.githubusercontent.com/16608659/82182893-3589bd80-990f-11ea-92d9-11cf5f73d046.png)

**Comment by lintaba** [comment]
upgrade to a later version. from 0.4.0 or 2.0.1 all works with php 7.4 .

**Comment by casperbakker** [comment]
Like @lintaba said, we added PHP 7.4 support in v0.4.0. You can also use v2.0 which also has 7.4 support.
